site_name: OHTK Docs
site_url: https://onehealthtoolkit.github.io/ohtk-docs/
nav:
    - Home: 'index.md'
    - Technical Docs: 'quickstart.md'
    - User Guide: 'userguide.md'
theme: readthedocs
markdown_extensions:
  - attr_list